services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: watchourmovie
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:pw@db:5432/watchourmovie

  frontend:
    build:
      context: ./front
      args:
        TMDB_TOKEN: ${TMDB_TOKEN}
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
